### ISSUE TITLE
Gamemode compatibility with scenario framework??

### ISSUE THREAD

**Issue by Pescadorr** [JiraF4/PlayableSelector#15]
its posible to make  compatibility with **scenario framework**. I have tried to add the components that were missing to the gamemode but it seems to work poorly and something is missing.

Thanks for the work, i make a missions with your system. [https://reforger.armaplatform.com/workshop/5F08018E538FD39D-NewEnfusionProject](url)

I can't get it to work the markers and briefing. 

I work to traslate the file Localization_Lobby.es_es.conf.

**Comment by JiraF4** [comment]
Finaly added
