### ISSUE TITLE
translation to other languages does not work

### ISSUE THREAD

**Issue by Pescadorr** [JiraF4/PlayableSelector#16]
Only in english and russian work well, for the rest you see the loading screen like this:

![20231211232816_1](https://github.com/JiraF4/PlayableSelector/assets/117852408/e0401517-bd64-4667-b8d3-5be29888d655)

Here I add the Spanish translation of the file: Localization_Lobby.es_es.conf
https://drive.google.com/file/d/1N1LQtpxINhqkjvfGtTaUJ_I2mS5NpSvu/view?usp=sharing
I hope it helps you and thanks for the work!!!

**Comment by JiraF4** [comment]
Well, it's new vanilla bug, for some reason translation does not fullback to english, we add Spanish translation and report it to Bohemia.
