### ISSUE TITLE
Does GetOnHandlePlayerKilled work? How to get player dead event?

### ISSUE THREAD

**Issue by scobaka** [JiraF4/PlayableSelector#47]
I try create player K/D statistics, but cant get player death event.
I create child class of PS_GameModeCoopClass and overide HandlePlayerKilled - it doesnt work.
I take handle by GetOnHandlePlayerKilled() and subscribe to it - it doesnt work.
HandlePlayerKilled calls when i use Respawn button in game, but it doesnt call when player dies in game. 
How can i get player dead event?

P.S.
HandlePlayerKilled works without this mod.

**Comment by JiraF4** [comment]
Engine just doesn't raise this event, even if I doesn't override method at all, idk why.
https://discord.com/channels/105462288051380224/1166105746757398558/1266526473037156352
https://discord.com/channels/105462288051380224/1166105746757398558/1266623498592321558
This strange issue frustrating me...
Also it for work on some maps and on some doesn't.

Coalition use base class override, with is for some reason works, it's broken only on inherited classes. ¯\(°_o)/¯

**Comment by scobaka** [comment]
Ok. I understand. I use crutch for kills counting with "SCR_CharacterDamageManagerComponent.GetOnDamage()"
